<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>TXT</string>
		<string>PRG</string>
		<string>VRB</string>
	</array>
	<key>name</key>
	<string>dbc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.dbc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.import.dbc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s+(INC)\s*(.*)</string>
			<key>name</key>
			<string>meta.import.dbc</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#code</string>
		</dict>
		<dict/>
	</array>
	<key>repository</key>
	<dict>
		<key>all-types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#primative-types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#flags</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#verb-types</string>
				</dict>
			</array>
		</dict>
		<key>code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expressions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#all-types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^([\.\*\+]).*</string>
					<key>name</key>
					<string>comment.line.dbc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\s+(\.).*</string>
					<key>name</key>
					<string>comment.line.empty.dbc</string>
				</dict>
			</array>
		</dict>
		<key>dbc-functions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(CHOP|SQUEEZE|TRIM|MOD)\s+</string>
					<key>name</key>
					<string>constant.other.dbc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.dbc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.dbc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s+(SWITCH|MOVE|FILL|APPEND|CMOVE|MOVEFPTR|MOVELPTR|BUMP|LENSET|REPLACE|REP|SETLPTR|SETFPTR|ADD|SUB|MULT|DIVIDE|SEARCH|SCAN|MATCH|TYPE|FLAGREST|ENDSET|PAUSE|TRAPCLR|TRAPSET|TRAPREST|NORETURN|SHUTDOWN|CLOCK|RETCOUNT|TESTADR|MOVEADR|MOVEVL|TESTLABEL|MOVELABEL|CLOSE|PREP|READ|OPEN|ERASE|ROLLOUT|REPOSIT|LOADMOD|UNLOAD|PRINT|UPDATE|FPOSIT|UNPACK)\s+([A-Z0-9._$@]+(?!\w|\.|\$|=))?</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s+(SETFLAG|DISPLAY|SCRNSAVE|SCRNREST|DSPFNC|STATESAVE|STATEREST|PACK|LOAD|PACKLEN|STORE|CLEAR|SET|RESET|FLAGSAVE|CLEARADR|TRAPSAVE|TRAP|CLEARLABEL|GETPARM|SETVAR|SETVAR\.YN|WRITE|SETNVAR|SETCVAR)\s+</string>
					<key>name</key>
					<string>keyword.operator.dbc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s+#(IFDEF|IFNDEF|ENDIF|IFLABEL|IFNLABEL)(?!\w|\.|\$|=)</string>
					<key>name</key>
					<string>constant.other.dbc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s+(TSTAMP|DATE|TIME|ELAPSED|MESSAGE)\b</string>
					<key>name</key>
					<string>support.function.dbc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s+(LMOD|ULMOD)\s+</string>
					<key>name</key>
					<string>support.function.dbc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s+(NOBLANK|NOZERO)\s+</string>
					<key>name</key>
					<string>support.function.dbc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s+(RETURN.EOS|RETURN.NOTEOS)\s+</string>
					<key>name</key>
					<string>support.function.dbc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s+([A-Z0-9._$@]+(?!\w|\.|\$|=))\s+</string>
					<key>name</key>
					<string>entity.name.function.dbc</string>
				</dict>
			</array>
		</dict>
		<key>expressions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.dbc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.dbc</string>
						</dict>
					</dict>
					<key>name</key>
					<string>keyword.operator.dbc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#dbc-functions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#all-types</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>match</key>
							<string>([A-Z0-9._$@]+)</string>
							<key>name</key>
							<string>variable.parameter.dbc</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>flags</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w|\.|\$)(EOS|OVER|EQUAL|LESS|NULL)(?!\w|\.|\$|=)</string>
					<key>name</key>
					<string>storage.type.flags.dbc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\s+(DEBUG)\s+</string>
					<key>name</key>
					<string>storage.type.flags.dbc</string>
				</dict>
			</array>
		</dict>
		<key>functions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dbc-functions</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\s+(LOOP|WHILE|DO|FOR|REPEAT|CONTINUE|BREAK|UNTIL)\b</string>
					<key>name</key>
					<string>keyword.control.dbc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s+(RETURN|CHAIN|STOP|BEEP)\s+</string>
					<key>name</key>
					<string>keyword.control.dbc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s+([A-Z]\.)?(QUERY\.[A-Z0-9]{1,3}[1-9]{1,2})(?!\w|\.|\$|=)</string>
					<key>name</key>
					<string>support.function.dbc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.dbc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s+(CALL)\s([A-Z]\.)?((NEXT|BACK)\.[A-Z0-9]{1,3}[1-9]{1,2})(?!\w|\.|\$|=)</string>
					<key>name</key>
					<string>support.function.dbc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.dbc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.dbc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s+(CALL)\s([A-Z]\.)?((BK|PT|WT|RD|RT|OD|OP|RK|CO|CL|PR|UK|RP)[A-Z0-9]{1,3}[1-9]{0,2})(?!\w|\.|\$|=)</string>
					<key>name</key>
					<string>support.function.dbc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.dbc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.dbc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s+(GOTO|CALL|PERFORM|BRANCH)\s+([A-Z0-9._$@]+(?!\w|\.|\$|=))</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s+(ENDSWITCH|CASE|DEFAULT)\s+</string>
					<key>name</key>
					<string>keyword.control.dbc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s+(IF|ENDIF|ELSE)(?!\w|\.|\$|=)</string>
					<key>name</key>
					<string>keyword.control.dbc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w|\.|\$)(IF|ENDIF|ELSE)(?!\w|\.|\$|=)</string>
					<key>name</key>
					<string>keyword.control.dbc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!^)(\-|\+|\*|\/|%)</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.dbc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[0-9]*(\.[0-9]+)*\b</string>
					<key>name</key>
					<string>constant.numeric.dbc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\s(@)$</string>
					<key>name</key>
					<string>constant.numeric.dbc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w|\.|\$)(AND|OR|NOT)(?!\w|\.|\$|=)</string>
					<key>name</key>
					<string>keyword.operator.logical.dbc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.dbc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.dbc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.dbc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([A-Z0-9._$@]+(?!\w|\.|\$|=))\s+(ROUTINE|LROUTINE|VERB)(?!\w|\.|\$|=)\s([A-Z0-9._$@]+(?!\w|\.|\$|=|,))*</string>
					<key>name</key>
					<string>entity.name.function.dbc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s(ENDROUTINE)(?!\w|\.|\$|=)</string>
					<key>name</key>
					<string>entity.name.function.dbc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(=|!=|&lt;=|&gt;=|&lt;&gt;|&lt;|&gt;)</string>
					<key>name</key>
					<string>keyword.operator.comparison.dbc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\[|\])</string>
					<key>name</key>
					<string>meta.arrayindex.meta</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?!\w|\.|\$|=)\s(FROM|WITH|OF|IN)\s</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.ssraw</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.ssraw</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>keyword.operator.assignment.dbc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>keyword.operator.assignment.dbc</string>
						</dict>
						<dict>
							<key>match</key>
							<string>([A-Z0-9._$@]+)</string>
							<key>name</key>
							<string>variable.parameter.dbc</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>(?!\w|\.|\$|=)\s(TO|INTO)\s</string>
					<key>name</key>
					<string>keyword.operator.assignment.dbc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^([A-Z0-9_$@]+[A-Z0-9._$@]*(?!\w|\.|\$|=))$</string>
					<key>name</key>
					<string>entity.name.function.dbc</string>
				</dict>
			</array>
		</dict>
		<key>primative-types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\s(?:CHAR|FORM|EXTERNAL|EQU)\b</string>
					<key>name</key>
					<string>storage.type.primative.dbc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\s(LABEL|ARRAY|QUEUE|OBJECT)\s</string>
					<key>name</key>
					<string>storage.type.primative.dbc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\s(AFILE|IMAGE|FILE|IFILE|PFILE|DEVICE|RESOURCE|LIST)\s</string>
					<key>name</key>
					<string>storage.type.primative.dbc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\s(GCHAR|GFORM)\s</string>
					<key>name</key>
					<string>storage.type.primative.dbc</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.dbc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.dbc</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.dbc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>#.</string>
							<key>name</key>
							<string>constant.character.escape.dbc</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>verb-types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.verb.dbc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;!\w|\.|\$)(CVARLIT|NVARLIT|CVAR|NVAR|CNVARLIT|CNVAR|ANY|VAR|VARLIT)\b(\s|,|:)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.verb.dbc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;!\w|\.|\$)(LABEL|ARRAY|QUEUE|OBJECT)(?!\w|\.|\$|=)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.verb.dbc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;!\w|\.|\$)(CARRAY|NVARRAY|NARRAY)[1-3](?!\w|\.|\$|=)</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.dbc</string>
	<key>uuid</key>
	<string>822facbe-dd9d-4215-ab1d-d10a061a28ef</string>
</dict>
</plist>
